import type { AcademyProblem } from './problems'

/** 학원 시험지 사진 10장에 인쇄된 문제. 손글씨 답안과 채점 표시는 전사하지 않았다. */
export const ACADEMY_PROBLEMS: AcademyProblem[] = [
  {
    no: 201, source: 'academy', section: 'JDBC', sourceNo: 1, askType: '서술',
    title: 'PreparedStatement와 Statement',
    question: 'PreparedStatement와 Statement의 차이점을 쓰시오.',
    answer: [
      '`Statement`는 실행할 때 SQL 문자열을 전달한다.',
      '`PreparedStatement`는 SQL을 미리 준비하고 `?` 자리에 값을 바인딩해 실행한다. 같은 SQL을 값만 바꿔 반복 실행하기 쉽고 SQL 삽입 공격을 막는 데 도움이 된다.',
    ],
  },
  {
    no: 202, source: 'academy', section: 'JDBC', sourceNo: 2, askType: '서술',
    title: 'executeQuery()와 executeUpdate()',
    question: 'executeQuery()와 executeUpdate()의 차이점을 쓰시오.',
    answer: [
      '`executeQuery()`는 조회 SQL을 실행하고 조회 결과인 `ResultSet`을 반환한다.',
      '`executeUpdate()`는 `INSERT`·`UPDATE`·`DELETE` 등의 SQL을 실행하고 영향받은 행 수를 `int`로 반환한다.',
    ],
  },
  {
    no: 203, source: 'academy', section: 'JDBC', sourceNo: 3, askType: '서술',
    title: 'DriverManager.getConnection()의 역할',
    question: 'DriverManager.getConnection()의 역할을 쓰시오.',
    answer: ['데이터베이스 URL, 사용자 이름, 비밀번호를 받아 DB 연결을 만들고 `Connection` 객체를 반환한다.'],
  },
  {
    no: 204, source: 'academy', section: 'JDBC', sourceNo: 4, askType: '코드 작성',
    title: 'Statement를 PreparedStatement로 바꾸기',
    question: '아래 코드를 PreparedStatement 버전으로 작성하시오.',
    blocks: [{ label: '코드', lines: [
      'public int updateMember(Connection conn, int id) {',
      '    Statement stmt = null;',
      '    int result = 0;',
      '    String query = "UPDATE MEMBER SET BONUS = 0 WHERE ID = " + id;',
      '    try {',
      '        stmt = conn.createStatement();',
      '        result = stmt.executeUpdate(query);',
      '    } catch (SQLException e) {',
      '        e.printStackTrace();',
      '    } finally {',
      '        close(stmt);',
      '    }',
      '    return result;',
      '}',
    ] }],
    answer: [],
    answerCode: [
      'public int updateMember(Connection conn, int id) {',
      '    PreparedStatement pstmt = null;',
      '    int result = 0;',
      '    String query = "UPDATE MEMBER SET BONUS = 0 WHERE ID = ?";',
      '    try {',
      '        pstmt = conn.prepareStatement(query);',
      '        pstmt.setInt(1, id);',
      '        result = pstmt.executeUpdate();',
      '    } catch (SQLException e) {',
      '        e.printStackTrace();',
      '    } finally {',
      '        close(pstmt);',
      '    }',
      '    return result;',
      '}',
    ],
    explain: ['원본 코드에 있는 `close(...)` 보조 메서드를 그대로 사용한다.'],
  },
  {
    no: 205, source: 'academy', section: 'JDBC', sourceNo: 5, askType: '코드 작성',
    title: 'PreparedStatement를 Statement로 바꾸기',
    question: '아래 코드를 Statement 버전으로 작성하시오.',
    blocks: [{ label: '코드', lines: [
      'public ArrayList<Employee> selectEmployee(',
      '        Connection conn, String job, int salary) {',
      '    PreparedStatement pstmt = null;',
      '    ResultSet rset = null;',
      '    ArrayList<Employee> list = new ArrayList<Employee>();',
      '    String query = "SELECT EMP_NAME, JOB_NAME, SALARY FROM EMPLOYEE "',
      '        + "JOIN JOB USING(JOB_CODE) WHERE JOB_NAME = ? AND SALARY > ?";',
      '    try {',
      '        pstmt = conn.prepareStatement(query);',
      '        pstmt.setString(1, job);',
      '        pstmt.setInt(2, salary);',
      '        rset = pstmt.executeQuery();',
      '        while (rset.next()) {',
      '            list.add(new Employee(rset.getString("emp_name"),',
      '                rset.getString("job_name"), rset.getInt("salary")));',
      '            // Employee 클래스에 생성자 모두 있다고 가정',
      '        }',
      '    } catch (SQLException e) {',
      '        e.printStackTrace();',
      '    } finally {',
      '        close(rset);',
      '        close(pstmt);',
      '    }',
      '    return list;',
      '}',
    ] }],
    answer: [],
    answerCode: [
      'public ArrayList<Employee> selectEmployee(',
      '        Connection conn, String job, int salary) {',
      '    Statement stmt = null;',
      '    ResultSet rset = null;',
      '    ArrayList<Employee> list = new ArrayList<Employee>();',
      "    String escapedJob = job.replace(\"'\", \"''\");",
      '    String query = "SELECT EMP_NAME, JOB_NAME, SALARY FROM EMPLOYEE "',
      "        + \"JOIN JOB USING(JOB_CODE) WHERE JOB_NAME = '\"",
      "        + escapedJob + \"' AND SALARY > \" + salary;",
      '    try {',
      '        stmt = conn.createStatement();',
      '        rset = stmt.executeQuery(query);',
      '        while (rset.next()) {',
      '            list.add(new Employee(rset.getString("emp_name"),',
      '                rset.getString("job_name"), rset.getInt("salary")));',
      '        }',
      '    } catch (SQLException e) {',
      '        e.printStackTrace();',
      '    } finally {',
      '        close(rset);',
      '        close(stmt);',
      '    }',
      '    return list;',
      '}',
    ],
    explain: ['`Statement`에서는 완성된 SQL을 `executeQuery(query)`에 넘긴다.'],
    trap: '문자 값은 SQL에서 작은따옴표로 감싼다. 실제 앱에서는 문자열 연결 대신 `PreparedStatement`를 사용하는 편이 안전하다.',
  },
  {
    no: 206, source: 'academy', section: 'JDBC', sourceNo: 6, askType: '서술',
    title: 'ResultSet getXXX()의 두 인자형',
    question: 'ResultSet의 메서드 중 getXXX() (예: getInt(), getString(), getDate()) 메서드의 인자로는 String과 int가 들어갈 수 있다. 오버로딩된 두 메서드의 차이점을 쓰시오.',
    answer: ['`getXXX(String columnLabel)`은 열 이름 또는 별칭으로 값을 읽는다.', '`getXXX(int columnIndex)`는 SELECT 결과의 열 순서로 값을 읽으며 첫 열 번호는 1이다.'],
  },
  {
    no: 207, source: 'academy', section: 'JDBC', sourceNo: 7, askType: '코드 작성',
    title: '드라이버 등록 코드',
    question: '드라이버 등록에 사용되는 코드를 작성하시오.',
    answer: [],
    answerCode: ['Class.forName("oracle.jdbc.driver.OracleDriver");'],
    explain: ['수업에서 사용한 Oracle JDBC 드라이버 클래스 이름 기준이다.'],
  },
  {
    no: 208, source: 'academy', section: 'JDBC', sourceNo: 8, askType: '서술',
    title: 'setString()의 두 매개변수',
    question: 'PreparedStatement의 메서드 중 setXXX() (예: setString(), setInt(), setDate()) 메서드에는 두 개의 인자가 들어간다. 이 중 setString()만 가지고 볼 때, (1) 첫 번째 매개변수의 타입과 용도, (2) 두 번째 매개변수의 타입과 용도를 쓰시오.',
    answer: ['(1) `int`: SQL의 몇 번째 `?`에 값을 넣을지 나타내는 위치 번호. 1부터 시작한다.', '(2) `String`: 해당 `?`에 바인딩할 문자열 값.'],
  },
  {
    no: 209, source: 'academy', section: 'SQL', sourceNo: 1, askType: '서술',
    title: 'SQL 네 분류',
    question: 'SQL 분류(DQL, DDL, DML, TCL) 중 각 분류의 역할을 자세히 작성하고 해당 분류에 속해 있는 명령어를 모두 쓰시오.',
    answer: [
      'DQL: 데이터를 조회한다. `SELECT`.',
      'DDL: 데이터베이스 객체의 구조를 정의·변경·삭제한다. `CREATE`, `ALTER`, `DROP`, `TRUNCATE`, `RENAME`.',
      'DML: 테이블의 행을 추가·수정·삭제한다. `INSERT`, `UPDATE`, `DELETE`, `MERGE`.',
      'TCL: 트랜잭션의 변경을 확정·취소하거나 저장점을 만든다. `COMMIT`, `ROLLBACK`, `SAVEPOINT`.',
    ],
  },
  {
    no: 210, source: 'academy', section: 'SQL', sourceNo: 2, askType: '빈칸',
    title: '합집합과 교집합의 논리 연산자',
    question: '집합 연산자에 대한 설명을 아래의 소문제에 맞게 쓰시오. (a) 합집합을 의미하는 집합 연산자와 이를 논리 연산자로 표현한 것을 쓰시오. (b) 교집합을 의미하는 집합 연산자와 이를 논리 연산자로 표현한 것을 쓰시오.',
    answer: ['(a) `UNION`(중복 제거), 논리 조건으로는 `OR`에 대응한다.', '(b) `INTERSECT`, 논리 조건으로는 `AND`에 대응한다.'],
    trap: '`UNION ALL`은 중복을 유지한다. `OR`·`AND` 대응은 같은 행 집합에 조건을 적용할 때의 개념적 비교다.',
  },
  {
    no: 211, source: 'academy', section: 'SQL', sourceNo: 3, askType: '서술',
    title: 'SELECT 구문과 실행 순서',
    question: 'SELECT문의 전체 구문을 작성하고 각 절이 어떤 역할을 하는지와 실행 순서를 쓰시오.',
    answer: ['주요 논리 처리 순서: `FROM`·`JOIN` → `WHERE` → `GROUP BY` → `HAVING` → `SELECT` → `ORDER BY`.'],
    answerCode: [
      'SELECT [DISTINCT] 선택할 열·식',
      'FROM 테이블 [JOIN 다른 테이블 ON 연결 조건]',
      '[WHERE 행 조건]',
      '[GROUP BY 그룹 기준]',
      '[HAVING 그룹 조건]',
      '[ORDER BY 정렬 기준];',
    ],
    explain: ['`FROM`은 조회 대상을 정하고, `WHERE`는 행을 거른다. `GROUP BY`는 행을 묶고 `HAVING`은 그룹을 거른다. `SELECT`는 표시할 값을 고르고 `ORDER BY`는 결과를 정렬한다.'],
  },
  {
    no: 212, source: 'academy', section: 'SQL', sourceNo: 4, askType: '용어',
    title: 'SELECT 실행 결과의 이름',
    question: 'SELECT문을 수행하고 나면 나오는 결과물을 뭐라고 하는지 작성하시오.',
    answer: ['결과 집합(`Result Set`).'],
  },
  {
    no: 213, source: 'academy', section: 'SQL', sourceNo: 5, askType: '코드 작성',
    title: 'TEST 사용자 만들기',
    question: "사용자 명이 'TEST'이고 비밀번호가 '1234'인 계정을 생성하는 구문을 작성하시오. (이때, 사용자 명에 C##이 붙지 않는 설정은 이미 했다고 가정함)",
    answer: [], answerCode: ['CREATE USER TEST IDENTIFIED BY "1234";'],
    explain: ['비밀번호가 숫자로 시작하므로 Oracle에서는 큰따옴표로 감싼다.'],
  },
  {
    no: 214, source: 'academy', section: 'SQL', sourceNo: 6, askType: '코드 작성',
    title: 'TEST 사용자에게 권한 주기',
    question: "위에서 작성한 'TEST' 사용자에게 접속, 자원 저장, 뷰 생성 권한을 부여하는 구문을 작성하시오.",
    answer: [], answerCode: ['GRANT CONNECT, RESOURCE, CREATE VIEW TO TEST;'],
    explain: ['`CONNECT`와 `RESOURCE`는 수업에서 사용하는 역할(ROLE) 이름이다.'],
  },
  {
    no: 215, source: 'academy', section: 'SQL', sourceNo: 7, askType: '서술',
    title: 'TABLE 제약조건 다섯 가지',
    question: 'TABLE 제약조건의 모든 종류와 어떤 역할인지 설명하시오.',
    answer: [
      '`NOT NULL`: NULL 저장 금지.',
      '`UNIQUE`: 중복 값 금지. NULL 허용 여부는 DBMS 규칙을 따른다.',
      '`PRIMARY KEY`: 각 행을 고유하게 식별한다. 중복과 NULL 모두 금지.',
      '`FOREIGN KEY`: 다른 테이블의 키를 참조해 관계를 유지한다.',
      '`CHECK`: 지정한 조건에 맞는 값만 허용한다.',
    ],
    trap: '`DEFAULT`는 기본값 설정이며 제약조건 다섯 가지에는 포함하지 않는다.',
  },
  {
    no: 216, source: 'academy', section: 'SQL', sourceNo: 8, askType: '서술',
    title: 'TO_DATE의 YY와 RR',
    question: "TO_DATE() 함수에서 문자 데이터를 날짜 데이터로 바꿀 때 년도를 'YY' 또는 'RR'로 사용한다. 이 둘의 차이점을 적으시오.",
    answer: [
      '`YY`는 입력한 두 자리 연도를 현재 세기(앞 두 자리)에 붙인다.',
      '`RR`은 현재 연도의 뒤 두 자리와 입력값을 비교해 앞 세기·현재 세기·다음 세기 중 하나를 정한다. 따라서 오래된 두 자리 연도를 해석할 때 `YY`와 결과가 다를 수 있다.',
    ],
    explain: ['예를 들어 현재 연도가 2026년이면 `49`는 `YY`와 `RR` 모두 2049년, `75`는 `YY`로 2075년·`RR`로 1975년이 된다.'],
  },
  {
    no: 217, source: 'academy', section: 'SQL', sourceNo: 9, askType: '용어',
    title: '일정 간격의 번호를 만드는 객체',
    question: '순차적으로 일정 간격의 숫자(번호)를 발생시키는 객체는 무엇인지 적으시오.',
    answer: ['시퀀스(`SEQUENCE`).'],
  },
  {
    no: 218, source: 'academy', section: 'SQL', sourceNo: 10, askType: '오류',
    title: '급여 상위 3명의 ROWNUM',
    question: '급여를 많이 받는 상위 3명만 조회하고자 할 때 아래 구문처럼 작성하고 실행하면 의도한 대로 결과가 출력되지 않는다. 그 이유와 함께 옳은 결과물이 나오도록 쿼리문을 수정하시오.',
    blocks: [{ label: '코드', lines: [
      'SELECT ROWNUM, EMPNO, ENAME, SAL',
      'FROM EMP',
      'WHERE ROWNUM <= 3',
      'ORDER BY SAL DESC;',
    ] }],
    answer: ['`ROWNUM`이 먼저 세 행을 고른 다음 `ORDER BY`가 그 세 행만 정렬하므로 전체 급여 상위 3명이 아니다.'],
    answerCode: [
      'SELECT ROWNUM, EMPNO, ENAME, SAL',
      'FROM (SELECT EMPNO, ENAME, SAL',
      '      FROM EMP',
      '      ORDER BY SAL DESC)',
      'WHERE ROWNUM <= 3;',
    ],
  },
  {
    no: 219, source: 'academy', section: 'SQL', sourceNo: 11, askType: '서술',
    title: '네 가지 함수의 의미',
    question: '아래 함수 사용을 보고 각각 무엇을 의미하는지 작성하시오.',
    blocks: [{ label: '보기', lines: ['(a) LENGTH(ENAME)', '(b) NVL(COMM, 0)', '(c) ADD_MONTHS(SYSDATE, 2)', "(d) LPAD(EMAIL, 20, '#')"] }],
    answer: [
      '(a) `ENAME` 문자열의 길이를 구한다.',
      '(b) `COMM`이 NULL이면 0을, 아니면 `COMM` 값을 반환한다.',
      '(c) 현재 날짜에서 두 달 뒤의 날짜를 반환한다.',
      '(d) `EMAIL`을 전체 길이 20자로 맞추도록 왼쪽을 `#`으로 채운다. 이미 20자보다 길면 20자로 잘린다.',
    ],
  },
  {
    no: 220, source: 'academy', section: 'SQL', sourceNo: 12, askType: '코드 작성',
    title: 'EMP·DEPT ANSI 조인',
    question: '아래 두 테이블을 보고 사번, 사원 명, 부서 명, 직급 명, 급여, 근무 지역 조회 쿼리문을 ANSI 구문으로 작성하시오.',
    blocks: [{ label: '테이블', lines: [
      'EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)',
      'DEPT(DEPTNO, DNAME, LOC)',
      'DEPT: 10 ACCOUNTING NEW YORK / 20 RESEARCH DALLAS',
      '      30 SALES CHICAGO / 40 OPERATIONS BOSTON',
    ] }],
    answer: [],
    answerCode: [
      'SELECT E.EMPNO, E.ENAME, D.DNAME,',
      '       E.JOB, E.SAL, D.LOC',
      'FROM EMP E',
      'JOIN DEPT D ON E.DEPTNO = D.DEPTNO;',
    ],
    explain: ['시험지의 `EMP.JOB`을 직급 명으로 사용한다.'],
  },
  {
    no: 221, source: 'academy', section: 'SQL', sourceNo: 13, askType: '코드 작성',
    title: 'EMP·DEPT 오라클 조인',
    question: '위 쿼리문을 오라클 구문으로 바꿔 작성하시오.',
    blocks: [{ label: '테이블', lines: ['EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)', 'DEPT(DEPTNO, DNAME, LOC)'] }],
    answer: [],
    answerCode: [
      'SELECT E.EMPNO, E.ENAME, D.DNAME,',
      '       E.JOB, E.SAL, D.LOC',
      'FROM EMP E, DEPT D',
      'WHERE E.DEPTNO = D.DEPTNO;',
    ],
  },
  {
    no: 222, source: 'academy', section: 'SQL', sourceNo: 14, askType: '서술',
    title: 'SEQUENCE 옵션',
    question: 'SEQUENCE에서 사용되는 옵션을 모두 적으시오.',
    answer: [
      '`START WITH`: 시작값, `INCREMENT BY`: 증감 간격.',
      '`MINVALUE`·`NOMINVALUE`, `MAXVALUE`·`NOMAXVALUE`: 최솟값과 최댓값.',
      '`CYCLE`·`NOCYCLE`: 한계 도달 시 순환 여부.',
      '`CACHE`·`NOCACHE`: 번호를 미리 메모리에 확보할지 여부.',
      '`ORDER`·`NOORDER`: 요청 순서대로 번호를 생성할지 여부.',
    ],
  },
  {
    no: 223, source: 'academy', section: 'SQL', sourceNo: 15, askType: '고르기',
    title: 'SQL O/X 네 문항',
    question: '아래 소문제를 보고 옳은 답에 표시하시오.',
    blocks: [{ label: '보기', lines: [
      '(a) 그룹함수 COUNT(*)를 조회하면 NULL을 제외한 행의 개수가 조회된다. (O / X)',
      '(b) RESULT SET은 항상 0개 이상의 행을 반환한다. (O / X)',
      '(c) JOIN은 FOREIGN KEY 제약조건이 걸려있으면 가능한 구문이다. (O / X)',
      '(d) ALTER 명령어는 데이터를 수정하는 명령어이다. (O / X)',
    ] }],
    answer: ['(a) X — `COUNT(*)`는 NULL을 포함해 행 자체를 센다.', '(b) O — 결과 행은 0개일 수도 있다.', '(c) X — 외래키 제약이 없어도 조건에 맞게 조인할 수 있다.', '(d) X — `ALTER`는 객체 구조를 바꾼다.'],
  },
  {
    no: 224, source: 'academy', section: 'SQL', sourceNo: 16, askType: '서술',
    title: 'FOREIGN KEY의 삭제 옵션',
    question: 'FOREIGN KEY 제약조건의 삭제 옵션을 모두 쓰고 각 옵션의 설명까지 작성하시오.',
    answer: [
      '`ON DELETE CASCADE`: 부모 행을 삭제하면 참조하는 자식 행도 함께 삭제한다.',
      '`ON DELETE SET NULL`: 부모 행을 삭제하면 자식 행의 외래키 값을 NULL로 바꾼다. 해당 열이 NULL을 허용해야 한다.',
      '삭제 옵션을 지정하지 않으면 자식 행이 참조 중인 부모 행의 삭제가 거부된다.',
    ],
  },
  {
    no: 225, source: 'academy', section: 'SQL', sourceNo: 17, askType: '빈칸',
    title: '서브쿼리와 SELECT문',
    question: '아래 빈칸에 알맞은 단어를 작성하시오.',
    blocks: [{ label: '문제', lines: [
      '______란, 다른 SQL의 내부에 작성하는 SQL(SELECT문)을 지칭하는 용어이고',
      '______란, 하나 이상의 테이블에서 데이터를 조회하기 위해 사용하는 구문이다.',
    ] }],
    answer: ['첫 번째: 서브쿼리(`SUBQUERY`).', '두 번째: `SELECT`문(조회문).'],
  },
  {
    no: 226, source: 'academy', section: 'SQL', sourceNo: 18, askType: '서술',
    title: '두 INSERT문의 차이',
    question: '두 INSERT문의 차이점을 쓰시오. `INSERT INTO 테이블명 VALUES(입력 값)`과 `INSERT INTO 테이블명(컬럼명) VALUES(입력 값)`.',
    answer: [
      '열 목록이 없으면 테이블의 모든 열에 정의된 순서대로 값을 제공해야 한다.',
      '열 목록이 있으면 지정한 열에 지정한 순서대로 값을 넣는다. 생략한 열에는 기본값이 적용되거나 NULL이 들어가며, 필수 열 조건을 위반하면 오류가 난다.',
    ],
  },
  {
    no: 227, source: 'academy', section: 'SQL', sourceNo: 19, askType: '코드 작성',
    title: '13번 글의 댓글 조회',
    question: '아래 테이블 구조를 참고하여 요구사항에 맞는 쿼리문을 작성하시오. 13번 글에 달린 댓글을 조회한다. 글 작성자 아이디, 작성자 닉네임, 게시글 제목, 게시글 내용, 글 조회수, 글 수정 일자, 댓글 번호, 댓글 작성자 닉네임, 댓글 내용, 댓글 수정 일자를 조회한다.',
    blocks: [{ label: '테이블', lines: [
      'BOARD(BOARD_ID, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT,',
      '      BOARD_COUNT, BOARD_CREATE_DATE, BOARD_MODIFY_DATE)',
      'MEMBER(ID, PWD, NAME, NICKNAME, EMAIL, GENDER, AGE,',
      '       PHONE, ADDRESS, ENROLL_DATE, UPDATE_DATE)',
      'REPLY(REPLY_ID, REPLY_CONTENT, REF_BOARD_ID, REPLY_WRITER,',
      '      REPLY_CREATE_DATE, REPLY_MODIFY_DATE)',
      'BOARD.BOARD_WRITER = MEMBER.ID',
      'BOARD.BOARD_ID = REPLY.REF_BOARD_ID',
      'REPLY.REPLY_WRITER = MEMBER.ID',
    ] }],
    answer: [],
    answerCode: [
      'SELECT B.BOARD_WRITER, BW.NICKNAME AS BOARD_WRITER_NICKNAME,',
      '       B.BOARD_TITLE, B.BOARD_CONTENT, B.BOARD_COUNT,',
      '       B.BOARD_MODIFY_DATE, R.REPLY_ID,',
      '       RW.NICKNAME AS REPLY_WRITER_NICKNAME,',
      '       R.REPLY_CONTENT, R.REPLY_MODIFY_DATE',
      'FROM BOARD B',
      'JOIN MEMBER BW ON BW.ID = B.BOARD_WRITER',
      'JOIN REPLY R ON R.REF_BOARD_ID = B.BOARD_ID',
      'JOIN MEMBER RW ON RW.ID = R.REPLY_WRITER',
      'WHERE B.BOARD_ID = 13;',
    ],
    explain: ['`MEMBER`를 글 작성자와 댓글 작성자로 두 번 연결하므로 서로 다른 별칭을 쓴다.'],
  },
]
