export type Stars = 1 | 2 | 3

export type AskType = '서술형' | '단답형' | '코드작성' | '결과예측' | '빈칸'

export type QuizProblem = {
  no: number
  /** 어느 단원에서 나오는 문제인지 */
  unit: string
  /** 중요도 3이 가장 높다. 번호가 앞일수록 중요도가 높게 배치되어 있다. */
  stars: Stars
  points: number
  askType: AskType
  /** 목록(O 키)에 뜨는 짧은 제목 */
  title: string
  question: string
  questionCode?: string[]
  /** 버튼으로 한 개씩 열리는 힌트 */
  hints: string[]
  /** 이해가 안 되면 통째로 외울 한 문장 */
  memorize: string
  answer: string[]
  answerCode?: string[]
  /** 자가 채점용 체크 항목 */
  keywords: string[]
  trap?: string
  /** 지금 수준에서는 이유를 따지지 말고 외우고 넘어갈 문제 */
  rote?: boolean
  /**
   * 지난 시험에서 이 개념을 물어봤던 문제 번호.
   * 출제 범위를 확인하려고 남긴 기록이며 화면에는 띄우지 않는다.
   * 재시험은 문제가 전부 바뀌므로 "또 나온다"는 신호로 쓰면 안 된다.
   */
  fromExam?: number
}

/**
 * 지난 Java 시험(기초·심화 10문제)의 출제 범위 안에서 뽑은 재시험 예상문제 50개.
 * 재시험은 문제가 전부 바뀌므로 배열 순서는 "또 나올 확률"이 아니라 개념의 중요도 순서다.
 * 앞쪽 10개는 이 범위의 뼈대가 되는 개념이고, 그 뒤로는 같은 단원에서 짝으로 출제되는
 * 개념을 중요한 것부터 놓았다.
 */
export const QUIZ_PROBLEMS: QuizProblem[] = [
  {
    no: 1,
    unit: 'OOP · 상속',
    stars: 3,
    points: 16,
    askType: '서술형',
    fromExam: 6,
    title: '오버라이딩의 정의와 성립 조건',
    question: '오버라이딩(Overriding)의 정의와 성립 조건을 모두 서술하시오.',
    hints: [
      '"모두"라고 했으니 조건을 최소 4개는 적어야 배점이 찹니다.',
      '메서드 한 개를 이루는 부품 세 가지를 떠올리세요. 이름, 매개변수, 반환형.',
    ],
    memorize: '이름·매개변수·반환형은 똑같이. 접근제어자는 넓게만. 예외는 좁게만.',
    answer: [
      '정의: 상위 클래스에서 물려받은 메서드를 하위 클래스에서 같은 모양으로 다시 정의하는 것이다.',
      '조건 1: 메서드 이름이 같아야 한다.',
      '조건 2: 매개변수의 타입·개수·순서가 같아야 한다.',
      '조건 3: 반환 타입이 같아야 한다.',
      '조건 4: 접근 제어자는 상위 클래스의 것보다 좁아질 수 없다.',
      '조건 5: 상위 클래스의 메서드보다 더 큰 예외를 선언할 수 없다.',
    ],
    keywords: [
      '상속받은 메서드를 다시 정의한다',
      '이름 동일',
      '매개변수 동일',
      '반환형 동일',
      '접근제어자는 좁아질 수 없다',
      '예외는 더 크게 선언 못 한다',
    ],
    trap: 'static·final·private 메서드는 오버라이딩할 수 없습니다. 이 한 줄을 마지막에 덧붙이면 점수가 더 붙습니다.',
  },
  {
    no: 2,
    unit: 'OOP · 캡슐화',
    stars: 3,
    points: 16,
    askType: '코드작성',
    fromExam: 9,
    title: 'DTO의 Getter · Setter 작성',
    question: '다음 DTO 클래스의 Getter/Setter를 모두 작성하시오.',
    questionCode: [
      'public class Player {',
      '    private String playerName;',
      '    private int playerNumber;',
      '}',
    ],
    hints: [
      '필드가 2개니까 메서드는 4개를 써야 합니다.',
      'getter는 매개변수가 없고 반환형이 필드 타입, setter는 반환형이 void입니다.',
    ],
    memorize: 'get은 받는 것 없이 필드를 돌려주고, set은 받아서 this.필드에 넣는다. setter는 void.',
    answer: [
      '필드 하나당 getter 1개와 setter 1개, 모두 4개를 씁니다.',
      '메서드 이름은 get/set 뒤에 필드명을 붙이되 첫 글자를 대문자로 바꿉니다.',
      'setter 안에서는 매개변수와 필드 이름이 같으므로 this로 필드를 가리킵니다.',
    ],
    answerCode: [
      'public String getPlayerName() {',
      '    return playerName;',
      '}',
      '',
      'public void setPlayerName(String playerName) {',
      '    this.playerName = playerName;',
      '}',
      '',
      'public int getPlayerNumber() {',
      '    return playerNumber;',
      '}',
      '',
      'public void setPlayerNumber(int playerNumber) {',
      '    this.playerNumber = playerNumber;',
      '}',
    ],
    keywords: [
      '메서드 4개를 모두 작성',
      'public 접근제어자',
      'getter 반환형이 필드 타입과 일치',
      'setter 반환형 void',
      'this.필드 = 매개변수',
    ],
    trap: '필드가 boolean일 때만 getter 이름이 isXxx()가 됩니다. 이 문제에서는 해당이 없습니다.',
  },
  {
    no: 3,
    unit: '람다 · 함수형',
    stars: 3,
    points: 11,
    askType: '서술형',
    fromExam: 1,
    title: '함수형 인터페이스와 @FunctionalInterface',
    question: '함수형 인터페이스와 @FunctionalInterface 어노테이션의 정의를 각각 서술하시오.',
    hints: [
      '"각각"이므로 답안을 두 덩어리로 나눠서 써야 합니다.',
      '앞은 "무엇인가", 뒤는 "무엇을 검사해 주는가"입니다.',
    ],
    memorize: '추상 메서드가 딱 하나면 함수형 인터페이스. @FunctionalInterface는 그게 맞는지 컴파일러가 검사하게 하는 표식.',
    answer: [
      '함수형 인터페이스는 추상 메서드를 정확히 하나만 가지는 인터페이스다.',
      '람다식이나 메서드 참조를 담을 수 있는 대상 타입이 된다.',
      '@FunctionalInterface는 그 인터페이스가 추상 메서드를 하나만 가지는지 컴파일러가 검사하게 하는 어노테이션이다.',
      '조건을 어기면 컴파일 오류가 나므로 설계 의도를 명확히 알리는 역할도 한다.',
    ],
    keywords: ['추상 메서드가 1개', '람다식의 대상 타입', '컴파일러가 검사', '어기면 컴파일 오류'],
    trap: 'default 메서드나 static 메서드가 여러 개 있어도, 추상 메서드가 하나면 함수형 인터페이스입니다.',
  },
  {
    no: 4,
    unit: '키워드 · final',
    stars: 3,
    points: 11,
    askType: '서술형',
    fromExam: 4,
    title: 'final이 쓰이는 3가지 경우',
    question: 'final 키워드가 사용되는 3가지 경우와 의미를 각각 서술하시오.',
    hints: ['문제가 개수를 알려줬습니다. 답안을 세 줄로 나눠 쓰세요.', 'final을 붙일 수 있는 자리는 변수, 메서드, 클래스입니다.'],
    memorize: 'final 변수는 값 못 바꾸고, final 메서드는 오버라이딩 못 하고, final 클래스는 상속 못 한다.',
    answer: [
      'final 변수: 한 번 값을 넣으면 다시 대입할 수 없다. 상수로 쓴다.',
      'final 메서드: 하위 클래스에서 오버라이딩할 수 없다.',
      'final 클래스: 다른 클래스가 상속(extends)할 수 없다.',
    ],
    keywords: ['변수 · 재대입 금지', '메서드 · 오버라이딩 금지', '클래스 · 상속 금지'],
    trap: 'final이 붙은 참조 변수도 "다른 객체를 가리키게" 바꾸지 못할 뿐, 그 객체 안의 값은 바뀔 수 있습니다.',
  },
  {
    no: 5,
    unit: 'OOP · 4대 특징',
    stars: 3,
    points: 11,
    askType: '서술형',
    fromExam: 5,
    title: '추상화란 무엇인가',
    question: '객체 지향 프로그래밍(OOP)의 특징 중 추상화(Abstraction)란 무엇인지 서술하시오.',
    hints: ['"공통점"과 "감춘다" 두 단어가 채점 키워드입니다.', '자바에서 추상화를 실제로 구현하는 두 문법을 덧붙이면 점수가 찹니다.'],
    memorize: '공통점만 뽑아 틀을 만들고 자세한 속은 감추는 것. 도구는 추상 클래스와 인터페이스.',
    answer: [
      '추상화는 여러 대상에서 공통되는 속성과 기능만 뽑아내 하나의 틀로 정의하는 것이다.',
      '사용자에게 필요한 부분만 드러내고 구체적인 구현 방법은 감춘다.',
      '자바에서는 추상 클래스(abstract class)와 인터페이스(interface)로 구현한다.',
    ],
    keywords: ['공통되는 속성과 기능을 뽑아낸다', '필요한 것만 드러내고 구현은 감춘다', '추상 클래스 · 인터페이스'],
    trap: '"복잡한 걸 단순하게 만드는 것"만 쓰면 점수가 반밖에 안 됩니다. 공통점 추출과 구현 은닉을 꼭 같이 쓰세요.',
  },
  {
    no: 6,
    unit: 'IO · 스트림',
    stars: 3,
    points: 11,
    askType: '빈칸',
    fromExam: 7,
    rote: true,
    title: 'IO 객체 세 가지 이름 대기',
    question: '(a), (b), (c)에 들어갈 알맞은 IO 객체명을 작성하시오.',
    questionCode: [
      '(a) : 파일을 읽기 위한 바이트 기반 스트림',
      '(b) : 키보드 입력 등을 받는 표준 입력 스트림',
      '(c) : 버퍼를 이용해 효율적으로 읽는 문자 기반 스트림',
    ],
    hints: ['이건 이해하는 문제가 아니라 이름을 아는 문제입니다.', '파일 → File..., 표준 입력 → System..., 버퍼 → Buffered...'],
    memorize: '파일 바이트는 FileInputStream, 키보드는 System.in, 버퍼 문자는 BufferedReader. 세 개를 소리 내서 외우세요.',
    answer: ['(a) FileInputStream', '(b) System.in', '(c) BufferedReader'],
    keywords: ['FileInputStream', 'System.in', 'BufferedReader'],
    trap: '바이트는 Stream, 문자는 Reader/Writer로 끝납니다. 이 규칙만 알아도 이름을 절반은 맞힙니다.',
  },
  {
    no: 7,
    unit: 'Java 기초',
    stars: 3,
    points: 6,
    askType: '단답형',
    fromExam: 2,
    title: '바이트코드를 실행하는 가상 기계',
    question:
      '자바를 실행하기 위한 가상의 기계로 OS에 관계없이 독립적으로 동작하며, 컴파일된 바이트코드(.class)를 실행하고 Stack·Heap·Static 등의 메모리 영역을 관리하는 것은 무엇인가?',
    hints: ['답은 알파벳 세 글자입니다.', '"가상 기계"를 영어로 옮기면 Virtual Machine입니다.'],
    memorize: 'JVM = 자바 가상 머신. 바이트코드를 실행하고 메모리를 관리한다.',
    answer: ['JVM (Java Virtual Machine, 자바 가상 머신)'],
    keywords: ['JVM 또는 자바 가상 머신'],
    trap: 'JDK는 개발 도구 묶음, JRE는 실행 환경, JVM은 실제로 바이트코드를 돌리는 가상 머신입니다. 셋을 헷갈리면 0점입니다.',
  },
  {
    no: 8,
    unit: 'Java 기초',
    stars: 3,
    points: 6,
    askType: '코드작성',
    fromExam: 3,
    title: 'main 메서드 선언부',
    question: '자바 애플리케이션 수행에 필요한 main 메서드의 선언부를 작성하시오.',
    hints: ['다섯 조각으로 되어 있습니다. 접근제어자, static, 반환형, 이름, 매개변수.', '매개변수는 문자열 배열입니다.'],
    memorize: 'public static void main(String[] args) 한 줄을 통째로 외우세요. 손으로 다섯 번 쓰면 끝납니다.',
    answer: ['public static void main(String[] args)'],
    answerCode: ['public static void main(String[] args) {', '    // 프로그램이 시작되는 자리', '}'],
    keywords: ['public', 'static', 'void', 'main', 'String[] 매개변수'],
    trap: 'args라는 이름만 바꿀 수 있습니다. public, static, void, String[]은 하나라도 틀리면 실행되지 않습니다.',
  },
  {
    no: 9,
    unit: '컬렉션 · Object',
    stars: 3,
    points: 6,
    askType: '빈칸',
    fromExam: 10,
    title: 'HashSet 중복 검사에 필요한 메서드',
    question:
      'HashSet에 저장되는 객체의 중복 검사를 위해서는 (a)와 (b) 메서드를 오버라이딩해야 한다. (a)는 값이 같은지 비교하는 메서드, (b)는 객체의 식별 번호를 반환하는 메서드이며, 둘 다 최상위 클래스인 (c)가 제공한다.',
    hints: ['(a)는 "같다"는 뜻의 영어 단어입니다.', '(c)는 자바의 모든 클래스가 물려받는 단 하나의 클래스입니다.'],
    memorize: '(a) equals, (b) hashCode, (c) Object. "이퀄즈·해시코드·오브젝트" 세 단어로 외우세요.',
    answer: ['(a) equals()', '(b) hashCode()', '(c) Object 클래스'],
    keywords: ['equals', 'hashCode', 'Object'],
    trap: '둘 중 하나만 오버라이딩하면 중복이 제대로 걸러지지 않습니다. 반드시 같이 오버라이딩한다고 덧붙이세요.',
  },
  {
    no: 10,
    unit: '스트림',
    stars: 3,
    points: 6,
    askType: '결과예측',
    fromExam: 8,
    title: '스트림 map · forEach 실행 결과',
    question: '다음 코드의 실행 결과를 작성하시오.',
    questionCode: [
      'List<String> names = Arrays.asList("짱구", "철수", "유리");',
      '',
      'names.stream()',
      '     .map(name -> name + "는 못말려")',
      '     .forEach(System.out::println);',
    ],
    hints: ['map은 각 원소를 바꾸고, forEach는 하나씩 출력합니다.', '원소가 3개니까 출력도 3줄입니다.'],
    memorize: 'map은 하나씩 바꾸기, forEach는 하나씩 꺼내 쓰기. 원소 개수만큼 줄이 나온다.',
    answer: ['짱구는 못말려', '철수는 못말려', '유리는 못말려'],
    keywords: ['3줄 모두 작성', '순서가 리스트 순서와 동일', '문자열이 정확히 이어붙음'],
    trap: '한 줄씩 줄바꿈해서 출력됩니다. println이므로 한 줄에 몰아 쓰면 틀립니다.',
  },
  {
    no: 11,
    unit: 'OOP · 메서드',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: '오버로딩의 정의와 성립 조건',
    question: '오버로딩(Overloading)의 정의와 성립 조건을 서술하시오.',
    hints: ['오버라이딩과 짝으로 나오는 문제입니다. 이쪽은 "같은 클래스 안"입니다.', '무엇이 같고 무엇이 달라야 하는지를 나눠 쓰세요.'],
    memorize: '같은 클래스에서 이름은 같고 매개변수만 다르게. 반환형만 다른 것은 오버로딩이 아니다.',
    answer: [
      '정의: 같은 클래스 안에서 이름이 같은 메서드를 매개변수를 다르게 하여 여러 개 정의하는 것이다.',
      '조건 1: 메서드 이름이 같아야 한다.',
      '조건 2: 매개변수의 타입·개수·순서 중 하나 이상이 달라야 한다.',
      '조건 3: 반환 타입만 다른 것은 오버로딩으로 인정되지 않는다.',
    ],
    keywords: ['같은 클래스 안', '이름 동일', '매개변수가 달라야 한다', '반환형만 다른 것은 안 된다'],
    trap: '매개변수 이름만 바꾸는 것도 오버로딩이 아닙니다. 타입·개수·순서가 달라야 합니다.',
  },
  {
    no: 12,
    unit: 'OOP · 메서드',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: '오버로딩과 오버라이딩의 차이',
    question: '오버로딩(Overloading)과 오버라이딩(Overriding)의 차이를 비교하여 서술하시오.',
    hints: ['비교 문제는 항목을 나눠 쓰면 점수가 잘 붙습니다. 위치, 이름, 매개변수, 목적.', '한쪽은 상속이 필요하고 한쪽은 필요 없습니다.'],
    memorize: '오버로딩은 한 클래스 안 새 메서드, 오버라이딩은 부모 메서드 갈아끼우기.',
    answer: [
      '오버로딩은 같은 클래스 안에서, 오버라이딩은 상속 관계의 하위 클래스에서 일어난다.',
      '오버로딩은 매개변수가 달라야 하고, 오버라이딩은 매개변수가 같아야 한다.',
      '오버로딩은 반환형이 달라도 되고, 오버라이딩은 반환형이 같아야 한다.',
      '오버로딩은 비슷한 기능을 편하게 여러 형태로 쓰기 위함이고, 오버라이딩은 물려받은 기능을 새로 정의하기 위함이다.',
    ],
    keywords: ['같은 클래스 vs 상속 관계', '매개변수 다름 vs 같음', '목적의 차이'],
    trap: '둘을 거꾸로 쓰는 실수가 가장 많습니다. "오버라이딩 = 상속" 한 쌍만 확실히 잡아 두세요.',
  },
  {
    no: 13,
    unit: 'OOP · 4대 특징',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: '캡슐화란 무엇인가',
    question: '객체 지향 프로그래밍의 특징 중 캡슐화(Encapsulation)란 무엇인지 서술하시오.',
    hints: ['"묶는다"와 "감춘다" 두 가지를 모두 써야 합니다.', '9번 문제에서 본 private과 getter/setter가 여기에 쓰입니다.'],
    memorize: '데이터와 기능을 클래스 하나로 묶고, 필드는 private으로 감추고 getter/setter로만 열어준다.',
    answer: [
      '캡슐화는 데이터(필드)와 그 데이터를 다루는 기능(메서드)을 하나의 클래스로 묶는 것이다.',
      '외부에서 내부 데이터에 직접 접근하지 못하도록 감춘다(정보 은닉).',
      '자바에서는 필드를 private으로 선언하고 public getter/setter로만 접근하게 하여 구현한다.',
    ],
    keywords: ['데이터와 기능을 하나로 묶는다', '정보 은닉', 'private 필드 + public getter/setter'],
    trap: '추상화와 헷갈리기 쉽습니다. 캡슐화는 "묶고 감추기", 추상화는 "공통점만 뽑기"입니다.',
  },
  {
    no: 14,
    unit: 'OOP · 4대 특징',
    stars: 3,
    points: 6,
    askType: '단답형',
    rote: true,
    title: 'OOP의 4대 특징',
    question: '객체 지향 프로그래밍(OOP)의 4가지 특징을 모두 쓰시오.',
    hints: ['이 문제는 무조건 외우는 문제입니다.', '"캡·상·다·추"로 외우면 빠집니다.'],
    memorize: '캡슐화, 상속, 다형성, 추상화. "캡상다추" 네 글자로 외우세요.',
    answer: ['캡슐화(Encapsulation)', '상속(Inheritance)', '다형성(Polymorphism)', '추상화(Abstraction)'],
    keywords: ['캡슐화', '상속', '다형성', '추상화'],
    trap: '각각 한 줄 설명을 붙이라는 문제로도 자주 바뀝니다. 네 개 모두 한 줄 정의까지 준비하세요.',
  },
  {
    no: 15,
    unit: 'OOP · 상속',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: '상속의 정의와 장점',
    question: '상속(Inheritance)의 정의와 장점을 서술하고, 사용하는 키워드를 쓰시오.',
    hints: ['정의 · 장점 · 키워드 세 칸을 채우는 문제입니다.', '장점은 "다시 안 써도 된다"가 핵심입니다.'],
    memorize: '상속은 부모 클래스의 필드와 메서드를 물려받는 것. 키워드는 extends. 자바는 클래스 다중 상속 불가.',
    answer: [
      '정의: 기존 클래스(상위 클래스)의 필드와 메서드를 새로운 클래스(하위 클래스)가 물려받는 것이다.',
      '키워드: class 자식 extends 부모 형태로 선언한다.',
      '장점 1: 이미 작성한 코드를 다시 쓰지 않아도 되어 코드 재사용성이 높아진다.',
      '장점 2: 공통 기능을 상위 클래스에서 한 번만 고치면 되어 유지보수가 쉬워진다.',
    ],
    keywords: ['물려받는다', 'extends', '코드 재사용', '유지보수 용이'],
    trap: '자바는 클래스를 여러 개 동시에 상속할 수 없습니다(단일 상속). 인터페이스는 여러 개 구현할 수 있습니다.',
  },
  {
    no: 16,
    unit: 'OOP · 4대 특징',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: '다형성이란 무엇인가',
    question: '다형성(Polymorphism)이란 무엇인지 서술하고, 예를 들어 설명하시오.',
    hints: ['"하나의 타입으로 여러 객체를 다룬다"가 핵심 문장입니다.', '예시는 Animal a = new Dog(); 한 줄이면 충분합니다.'],
    memorize: '부모 타입 변수 하나로 여러 자식 객체를 담을 수 있는 성질. Animal a = new Dog();',
    answer: [
      '다형성은 하나의 타입(상위 클래스나 인터페이스)으로 여러 하위 클래스 객체를 다룰 수 있는 성질이다.',
      '상위 타입 변수에 하위 클래스 객체를 담는 것을 업캐스팅이라 한다.',
      '예: Animal a = new Dog(); 로 선언한 뒤 a.sound()를 호출하면 Dog가 오버라이딩한 메서드가 실행된다.',
      '덕분에 같은 코드로 여러 종류의 객체를 다룰 수 있어 확장에 유리하다.',
    ],
    keywords: ['하나의 타입으로 여러 객체', '업캐스팅', '오버라이딩된 메서드가 실행된다', '예시 코드'],
    trap: '다형성 문제는 실행 결과 예측 문제(41번)로도 나옵니다. "실제로 실행되는 것은 자식 메서드"를 꼭 기억하세요.',
  },
  {
    no: 17,
    unit: 'Java 기초',
    stars: 3,
    points: 11,
    askType: '서술형',
    rote: true,
    title: '접근 제어자 4가지',
    question: '자바의 접근 제어자 4가지를 쓰고 각각의 접근 범위를 서술하시오.',
    hints: ['좁은 것부터 넓은 것 순서로 쓰면 빠뜨리지 않습니다.', 'default는 키워드를 쓰지 않는 경우입니다.'],
    memorize: 'private(같은 클래스) → default(같은 패키지) → protected(같은 패키지 + 자식) → public(전부). 좁은 순서로 외우세요.',
    answer: [
      'private: 같은 클래스 안에서만 접근할 수 있다.',
      'default(아무것도 안 붙임): 같은 패키지 안에서만 접근할 수 있다.',
      'protected: 같은 패키지와, 다른 패키지라도 상속받은 하위 클래스에서 접근할 수 있다.',
      'public: 어디에서든 접근할 수 있다.',
    ],
    keywords: ['private · 같은 클래스', 'default · 같은 패키지', 'protected · 같은 패키지 + 하위 클래스', 'public · 전체'],
    trap: 'default는 "default"라고 써 넣는 키워드가 아니라 아무것도 안 붙인 상태입니다.',
  },
  {
    no: 18,
    unit: '키워드 · static',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: 'static의 의미와 특징',
    question: 'static 키워드의 의미와 static 변수·메서드의 특징을 서술하시오.',
    hints: ['8번 main 메서드에도 static이 붙어 있습니다. 왜 붙어 있을까요.', '"객체를 만들지 않아도"가 핵심 표현입니다.'],
    memorize: 'static은 객체를 만들지 않아도 쓸 수 있고, 모든 객체가 하나를 같이 쓴다. 클래스이름.멤버로 접근.',
    answer: [
      'static은 클래스가 메모리에 올라갈 때 딱 한 번 만들어지는 멤버에 붙이는 키워드다.',
      'static 변수는 모든 객체가 하나의 값을 공유한다.',
      'static 메서드는 객체를 생성하지 않아도 클래스이름.메서드() 형태로 호출할 수 있다.',
      'static 메서드 안에서는 객체마다 따로 있는 인스턴스 변수를 직접 쓸 수 없다.',
    ],
    keywords: ['객체 생성 없이 사용', '모든 객체가 공유', '클래스이름.멤버 접근', '인스턴스 변수 직접 사용 불가'],
    trap: 'main이 static인 이유가 이 문제의 단골 확장입니다. "객체를 만들기 전에 실행되어야 하므로"라고 답하세요.',
  },
  {
    no: 19,
    unit: 'OOP · 클래스',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: '생성자의 정의와 규칙',
    question: '생성자(Constructor)의 정의와 작성 규칙을 서술하고, 기본 생성자에 대해 설명하시오.',
    hints: ['생성자는 메서드처럼 생겼지만 두 가지가 다릅니다. 이름과 반환형.', '기본 생성자는 "언제 자동으로 생기는가"가 포인트입니다.'],
    memorize: '생성자는 객체를 만들 때 딱 한 번 실행된다. 이름은 클래스와 같고 반환형이 없다. 생성자를 하나도 안 쓰면 기본 생성자가 자동으로 생긴다.',
    answer: [
      '정의: 객체가 생성될 때 딱 한 번 자동으로 호출되어 필드를 초기화하는 특별한 메서드다.',
      '규칙 1: 이름이 클래스 이름과 완전히 같아야 한다.',
      '규칙 2: 반환 타입을 쓰지 않는다(void도 쓰지 않는다).',
      '기본 생성자: 클래스에 생성자를 하나도 작성하지 않으면 매개변수가 없는 생성자가 컴파일러에 의해 자동으로 만들어진다.',
    ],
    keywords: ['객체 생성 시 자동 호출', '클래스 이름과 동일', '반환 타입 없음', '기본 생성자 자동 생성'],
    trap: '생성자를 하나라도 직접 만들면 기본 생성자는 자동으로 만들어지지 않습니다. 이 한 줄이 배점입니다.',
  },
  {
    no: 20,
    unit: 'Java 기초',
    stars: 2,
    points: 6,
    askType: '서술형',
    title: 'this와 super의 차이',
    question: 'this와 super의 의미와 차이를 서술하시오.',
    hints: ['2번 문제의 setter에서 this를 썼습니다. 왜 썼는지 떠올려 보세요.', 'this()와 super()는 "생성자 호출"입니다.'],
    memorize: 'this는 자기 자신, super는 부모. this()는 내 다른 생성자, super()는 부모 생성자 호출.',
    answer: [
      'this는 현재 객체 자기 자신을 가리키는 참조 변수다. 매개변수와 필드 이름이 같을 때 필드를 가리키는 데 쓴다.',
      'super는 상위 클래스의 멤버를 가리키는 참조 변수다.',
      'this()는 같은 클래스의 다른 생성자를, super()는 상위 클래스의 생성자를 호출한다.',
      'this()와 super()는 반드시 생성자의 첫 줄에 와야 한다.',
    ],
    keywords: ['this = 자기 자신', 'super = 상위 클래스', 'this()/super()는 생성자 호출', '생성자 첫 줄'],
    trap: '생성자 안에서 super()를 쓰지 않아도 컴파일러가 부모의 기본 생성자를 자동으로 먼저 호출합니다.',
  },
  {
    no: 21,
    unit: 'OOP · 추상화',
    stars: 3,
    points: 16,
    askType: '서술형',
    title: '추상 클래스와 인터페이스의 차이',
    question: '추상 클래스(abstract class)와 인터페이스(interface)의 차이를 비교하여 서술하시오.',
    hints: ['비교 항목을 미리 정해 두세요. 키워드, 상속 개수, 가질 수 있는 멤버, 목적.', '한쪽만 여러 개를 동시에 쓸 수 있습니다.'],
    memorize: '추상 클래스는 하나만 상속(extends), 인터페이스는 여러 개 구현(implements). 추상 클래스는 일반 메서드·필드도 가진다.',
    answer: [
      '추상 클래스는 extends로 하나만 상속할 수 있고, 인터페이스는 implements로 여러 개를 동시에 구현할 수 있다.',
      '추상 클래스는 일반 필드와 일반 메서드, 생성자를 가질 수 있지만 인터페이스는 상수와 추상 메서드가 기본이다.',
      '추상 클래스는 공통 기능을 물려주는 것이 목적이고, 인터페이스는 "이 기능은 반드시 구현하라"는 규격을 정하는 것이 목적이다.',
      '둘 다 직접 객체를 생성할 수 없다.',
    ],
    keywords: ['extends 1개 vs implements 여러 개', '일반 메서드·필드 보유 여부', '목적: 공통 기능 vs 규격', '둘 다 객체 생성 불가'],
    trap: 'Java 8부터 인터페이스에도 default·static 메서드를 넣을 수 있습니다. 여유가 있으면 한 줄 덧붙이세요.',
  },
  {
    no: 22,
    unit: 'OOP · 추상화',
    stars: 2,
    points: 11,
    askType: '서술형',
    title: '인터페이스의 정의와 특징',
    question: '인터페이스(interface)의 정의와 특징을 서술하시오.',
    hints: ['"규격"이나 "약속"이라는 단어를 쓰세요.', '구현하는 쪽에서 무엇을 반드시 해야 하는지 쓰면 됩니다.'],
    memorize: '인터페이스는 메서드 이름만 정해 놓은 약속. implements한 클래스는 그 메서드를 반드시 구현해야 한다.',
    answer: [
      '인터페이스는 클래스가 반드시 구현해야 할 메서드를 미리 정해 놓은 규격이다.',
      '모든 필드는 자동으로 public static final 상수가 되고, 메서드는 자동으로 public abstract가 된다.',
      'implements 키워드로 구현하며, 한 클래스가 여러 인터페이스를 동시에 구현할 수 있다.',
      '구현 클래스는 인터페이스의 추상 메서드를 모두 오버라이딩해야 한다.',
    ],
    keywords: ['구현해야 할 규격', 'public abstract 메서드', 'implements', '여러 개 구현 가능', '모두 오버라이딩 필수'],
    trap: '"인터페이스는 다중 상속을 지원한다"는 표현도 맞습니다. 클래스가 안 되는 것을 인터페이스가 해 줍니다.',
  },
  {
    no: 23,
    unit: '람다 · 함수형',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: '람다식이란 무엇인가',
    question: '람다식(Lambda Expression)이란 무엇인지 서술하고 기본 형식을 쓰시오.',
    hints: ['3번 문제의 함수형 인터페이스와 짝입니다.', '10번 문제 코드의 name -> name + "는 못말려" 부분이 람다식입니다.'],
    memorize: '람다식은 이름 없는 메서드를 식 하나로 줄여 쓴 것. 형식은 (매개변수) -> { 실행할 내용 }',
    answer: [
      '람다식은 메서드를 하나의 식으로 간결하게 표현한 것으로, 이름 없는 익명 함수라고도 한다.',
      '기본 형식은 (매개변수) -> { 실행할 문장 } 이다.',
      '실행 문장이 한 줄이면 중괄호와 return을 생략할 수 있고, 매개변수가 하나면 괄호도 생략할 수 있다.',
      '함수형 인터페이스(추상 메서드가 하나인 인터페이스)의 구현 객체로 사용된다.',
    ],
    answerCode: ['// 기본 형식', '(매개변수) -> { 실행할 문장 }', '', '// 줄여 쓴 형태', 'name -> name + "는 못말려"'],
    keywords: ['익명 함수', '(매개변수) -> { 실행문 }', '생략 규칙', '함수형 인터페이스와 함께 쓴다'],
    trap: '화살표는 -> 이고, => 가 아닙니다. 서술형에서도 기호를 정확히 쓰세요.',
  },
  {
    no: 24,
    unit: '람다 · 함수형',
    stars: 2,
    points: 11,
    askType: '빈칸',
    rote: true,
    title: '자바가 기본 제공하는 함수형 인터페이스',
    question: '자바가 기본 제공하는 대표적인 함수형 인터페이스 4가지의 이름과 추상 메서드, 용도를 쓰시오.',
    hints: ['이건 표를 통째로 외우는 문제입니다.', '받는 게 있는지, 돌려주는 게 있는지로 구분하면 외우기 쉽습니다.'],
    memorize: '받고 돌려주면 Function, 받기만 하면 Consumer, 주기만 하면 Supplier, 참거짓만 돌려주면 Predicate.',
    answer: [
      'Function<T,R> : apply(T t) · 값을 받아 다른 값으로 바꿔서 반환한다.',
      'Consumer<T> : accept(T t) · 값을 받아 소비만 하고 반환값이 없다.',
      'Supplier<T> : get() · 받는 값 없이 값을 만들어 반환한다.',
      'Predicate<T> : test(T t) · 값을 받아 참/거짓(boolean)을 반환한다.',
    ],
    keywords: ['Function · apply', 'Consumer · accept', 'Supplier · get', 'Predicate · test'],
    trap: '스트림의 map은 Function, forEach는 Consumer, filter는 Predicate를 받습니다. 연결해서 외우면 두 문제를 한 번에 잡습니다.',
  },
  {
    no: 25,
    unit: '스트림',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: '스트림의 3단계 처리 과정',
    question: '스트림(Stream)이란 무엇인지 서술하고, 스트림의 3단계 처리 과정을 쓰시오.',
    hints: ['10번 문제 코드를 세 덩어리로 잘라 보세요. stream() / map() / forEach()', '마지막 단계는 딱 한 번만 올 수 있습니다.'],
    memorize: '스트림은 컬렉션 데이터를 물 흐르듯 처리하는 도구. 생성 → 중간 연산 → 최종 연산 3단계.',
    answer: [
      '스트림은 컬렉션이나 배열의 데이터를 반복문 없이 일괄 처리할 수 있게 해 주는 도구다.',
      '1단계 생성: stream() 등으로 스트림을 만든다.',
      '2단계 중간 연산: filter, map, sorted처럼 데이터를 걸러내거나 변환하며 여러 번 이어 붙일 수 있다.',
      '3단계 최종 연산: forEach, collect, count처럼 결과를 만들어 내며 한 번만 올 수 있고 이때 실제 처리가 일어난다.',
    ],
    keywords: ['반복문 없이 일괄 처리', '생성', '중간 연산(filter·map)', '최종 연산(forEach·collect)', '최종 연산은 한 번'],
    trap: '중간 연산만 쓰면 아무것도 실행되지 않습니다. 최종 연산이 있어야 비로소 동작한다는 점이 배점입니다.',
  },
  {
    no: 26,
    unit: '스트림',
    stars: 2,
    points: 11,
    askType: '빈칸',
    rote: true,
    title: '스트림 주요 메서드의 역할',
    question: '스트림의 주요 메서드 filter, map, sorted, collect, forEach의 역할을 각각 쓰시오.',
    hints: ['다섯 개를 각각 한 줄씩만 쓰면 됩니다.', '앞의 셋은 중간 연산, 뒤의 둘은 최종 연산입니다.'],
    memorize: 'filter는 걸러내기, map은 바꾸기, sorted는 정렬, collect는 모아 담기, forEach는 하나씩 꺼내기.',
    answer: [
      'filter(조건): 조건을 만족하는 요소만 걸러낸다. (중간 연산)',
      'map(변환): 각 요소를 다른 값으로 바꾼다. (중간 연산)',
      'sorted(): 요소를 정렬한다. (중간 연산)',
      'collect(Collectors.toList()): 처리 결과를 리스트 등으로 모아 반환한다. (최종 연산)',
      'forEach(동작): 각 요소를 하나씩 꺼내 지정한 동작을 수행한다. (최종 연산)',
    ],
    keywords: ['filter · 조건에 맞는 것만', 'map · 변환', 'sorted · 정렬', 'collect · 결과 수집', 'forEach · 하나씩 처리'],
    trap: '중간 연산과 최종 연산을 구분해서 표시하면 점수가 더 붙습니다.',
  },
  {
    no: 27,
    unit: '컬렉션',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: 'List · Set · Map의 차이',
    question: '컬렉션 프레임워크의 List, Set, Map의 특징과 차이를 서술하시오.',
    hints: ['비교 기준은 세 가지입니다. 순서, 중복, 저장 방식.', '9번 문제의 HashSet이 여기의 Set입니다.'],
    memorize: 'List는 순서 있고 중복 허용, Set은 순서 없고 중복 불가, Map은 키와 값 한 쌍으로 저장하고 키는 중복 불가.',
    answer: [
      'List: 저장 순서가 유지되고 중복 저장을 허용한다. 대표 클래스는 ArrayList, LinkedList다.',
      'Set: 저장 순서가 유지되지 않고 중복을 허용하지 않는다. 대표 클래스는 HashSet, TreeSet이다.',
      'Map: 키(key)와 값(value)을 한 쌍으로 저장한다. 키는 중복될 수 없고 값은 중복될 수 있다. 대표 클래스는 HashMap이다.',
    ],
    keywords: ['List · 순서 O, 중복 O', 'Set · 순서 X, 중복 X', 'Map · 키-값 쌍, 키 중복 X', '대표 클래스 이름'],
    trap: 'Map은 Collection 인터페이스를 상속받지 않습니다. 컬렉션 프레임워크에는 속하지만 계열이 다릅니다.',
  },
  {
    no: 28,
    unit: '컬렉션',
    stars: 2,
    points: 11,
    askType: '서술형',
    title: 'ArrayList와 LinkedList의 차이',
    question: 'ArrayList와 LinkedList의 구조상 차이와 각각이 유리한 상황을 서술하시오.',
    hints: ['하나는 번호표가 붙은 사물함, 하나는 손을 잡고 늘어선 줄이라고 생각하세요.', '조회가 빠른 쪽과 삽입·삭제가 빠른 쪽이 갈립니다.'],
    memorize: 'ArrayList는 조회가 빠르고, LinkedList는 중간 삽입·삭제가 빠르다.',
    answer: [
      'ArrayList는 배열 구조라서 인덱스로 바로 찾아가므로 조회 속도가 빠르다.',
      '다만 중간에 데이터를 넣거나 지우면 뒤의 요소를 모두 밀어야 해서 느리다.',
      'LinkedList는 각 요소가 앞뒤 요소를 연결한 구조라서 중간 삽입·삭제가 빠르다.',
      '다만 특정 위치를 찾으려면 앞에서부터 따라가야 해서 조회가 느리다.',
    ],
    keywords: ['ArrayList · 배열 구조 · 조회 빠름', 'LinkedList · 연결 구조 · 삽입/삭제 빠름', '각각의 단점'],
    trap: '"어느 쪽이 더 좋은가"가 아니라 "상황에 따라 다르다"가 정답입니다.',
  },
  {
    no: 29,
    unit: '컬렉션 · Object',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: 'HashSet이 중복을 걸러내는 과정',
    question: 'HashSet이 객체의 중복을 판단하는 과정을 순서대로 서술하시오.',
    hints: ['9번 문제의 확장판입니다. equals와 hashCode가 어떤 순서로 쓰이는지가 답입니다.', '먼저 번호를 비교하고, 같으면 내용을 비교합니다.'],
    memorize: '먼저 hashCode()로 번호를 비교하고, 번호가 같으면 equals()로 내용을 비교한다. 둘 다 같으면 중복.',
    answer: [
      '1단계: 저장하려는 객체의 hashCode() 값을 구해 이미 저장된 객체들의 해시값과 비교한다.',
      '2단계: 해시값이 다르면 다른 객체로 보고 바로 저장한다.',
      '3단계: 해시값이 같으면 equals()로 내용이 같은지 비교한다.',
      '4단계: equals()가 true이면 같은 객체로 판단해 저장하지 않는다.',
      '그래서 사용자 정의 클래스를 HashSet에 담으려면 equals()와 hashCode()를 함께 오버라이딩해야 한다.',
    ],
    keywords: ['hashCode 먼저 비교', '해시값 같으면 equals 비교', '둘 다 같으면 중복 처리', '둘 다 오버라이딩 필요'],
    trap: '순서를 거꾸로 쓰면 감점입니다. hashCode가 먼저입니다.',
  },
  {
    no: 30,
    unit: '컬렉션',
    stars: 2,
    points: 6,
    askType: '빈칸',
    rote: true,
    title: 'HashMap 주요 메서드',
    question: 'HashMap에서 값을 저장·조회·삭제·확인할 때 쓰는 메서드를 각각 쓰시오.',
    hints: ['넣는 것과 꺼내는 것 두 개가 핵심입니다.', '영어 단어 그대로입니다.'],
    memorize: 'put(넣기), get(꺼내기), remove(지우기), containsKey(있는지 확인), size(개수), keySet(키 전체).',
    answer: [
      'put(키, 값): 키와 값을 저장한다. 같은 키로 넣으면 값이 덮어쓰기 된다.',
      'get(키): 키에 해당하는 값을 꺼낸다. 없으면 null을 반환한다.',
      'remove(키): 해당 키의 쌍을 삭제한다.',
      'containsKey(키): 그 키가 있는지 true/false로 알려준다.',
      'keySet(): 저장된 모든 키를 Set으로 반환한다.',
    ],
    keywords: ['put', 'get', 'remove', 'containsKey', 'keySet'],
    trap: '같은 키로 put을 두 번 하면 값이 두 개 쌓이는 게 아니라 나중 값으로 덮어써집니다.',
  },
  {
    no: 31,
    unit: '제네릭',
    stars: 2,
    points: 11,
    askType: '서술형',
    title: '제네릭의 정의와 장점',
    question: '제네릭(Generic)이란 무엇인지 서술하고 장점을 쓰시오.',
    hints: ['List<String>의 꺾쇠 안에 들어간 것이 제네릭입니다.', '장점은 "미리 막아 준다"입니다.'],
    memorize: '제네릭은 담을 데이터 타입을 미리 정해 두는 문법. 잘못된 타입을 컴파일 때 막아 주고 형변환이 필요 없어진다.',
    answer: [
      '제네릭은 클래스나 메서드에서 사용할 데이터 타입을 미리 지정해 두는 문법이다. 예: List<String>',
      '장점 1: 지정한 타입이 아닌 값을 넣으면 컴파일 단계에서 오류로 잡아 준다.',
      '장점 2: 꺼낼 때 형변환(캐스팅)을 하지 않아도 되어 코드가 간결해진다.',
      '장점 3: 실행 중에 발생할 타입 오류를 미리 막아 프로그램이 안정적이다.',
    ],
    keywords: ['타입을 미리 지정', '컴파일 시 타입 검사', '형변환 불필요', '<> 꺾쇠 표기'],
    trap: '제네릭에는 int 같은 기본형을 쓸 수 없습니다. Integer처럼 래퍼 클래스를 씁니다.',
  },
  {
    no: 32,
    unit: '컬렉션',
    stars: 2,
    points: 6,
    askType: '코드작성',
    title: '컬렉션을 순회하는 방법',
    question: 'List에 저장된 모든 요소를 출력하는 방법을 향상된 for문으로 작성하시오.',
    hints: ['형식은 for (타입 변수 : 컬렉션) 입니다.', '콜론 왼쪽이 하나씩 꺼내 담을 변수입니다.'],
    memorize: 'for (String name : names) { System.out.println(name); } 이 형태를 통째로 외우세요.',
    answer: [
      '향상된 for문(for-each)은 for (타입 변수명 : 컬렉션) 형태로 쓴다.',
      '컬렉션에서 요소를 하나씩 꺼내 변수에 담아 반복한다.',
      '인덱스를 직접 다루지 않아 코드가 짧고 실수가 적다.',
    ],
    answerCode: [
      'List<String> names = Arrays.asList("짱구", "철수", "유리");',
      '',
      'for (String name : names) {',
      '    System.out.println(name);',
      '}',
    ],
    keywords: ['for (타입 변수 : 컬렉션)', '중괄호 안 출력문', '타입이 요소 타입과 일치'],
    trap: '향상된 for문 안에서는 인덱스를 알 수 없고, 반복 중 컬렉션에서 요소를 지우면 오류가 납니다.',
  },
  {
    no: 33,
    unit: '예외 처리',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: 'try · catch · finally의 역할',
    question: '예외 처리 구문 try, catch, finally의 역할을 각각 서술하시오.',
    hints: ['세 칸을 채우는 문제입니다.', 'finally는 "어떤 경우에도"가 핵심입니다.'],
    memorize: 'try는 위험한 코드, catch는 터졌을 때 처리, finally는 터지든 말든 무조건 실행.',
    answer: [
      'try: 예외가 발생할 가능성이 있는 코드를 감싸는 블록이다.',
      'catch: try에서 예외가 발생했을 때 그 예외를 받아 처리하는 블록이다. 예외 종류별로 여러 개 쓸 수 있다.',
      'finally: 예외 발생 여부와 관계없이 반드시 실행되는 블록이다. 주로 파일이나 연결을 닫는 데 쓴다.',
      '예외 처리를 하면 오류가 나도 프로그램이 비정상 종료되지 않고 계속 진행할 수 있다.',
    ],
    keywords: ['try · 예외 발생 가능 코드', 'catch · 예외를 받아 처리', 'finally · 항상 실행', '비정상 종료 방지'],
    trap: 'catch가 실행되든 안 되든 finally는 실행됩니다. 43번 결과 예측 문제와 이어집니다.',
  },
  {
    no: 34,
    unit: '예외 처리',
    stars: 2,
    points: 6,
    askType: '서술형',
    title: 'throw와 throws의 차이',
    question: 'throw와 throws의 차이를 서술하시오.',
    hints: ['s 하나 차이지만 쓰는 자리가 다릅니다.', '하나는 메서드 선언부, 하나는 메서드 안입니다.'],
    memorize: 'throw는 예외를 지금 던지는 것, throws는 선언부에 "나 예외 던질 수 있어"라고 미리 알리는 것.',
    answer: [
      'throw는 메서드 안에서 예외 객체를 실제로 발생시켜 던질 때 쓴다. 예: throw new Exception();',
      'throws는 메서드 선언부에 붙여 이 메서드가 어떤 예외를 넘길 수 있는지 미리 알릴 때 쓴다.',
      'throws로 넘긴 예외는 그 메서드를 호출한 쪽에서 처리해야 한다.',
    ],
    keywords: ['throw · 메서드 안에서 예외 발생', 'throws · 선언부에서 예외 위임', '호출한 쪽이 처리'],
    trap: 'throw 뒤에는 예외 객체 하나, throws 뒤에는 예외 클래스 이름이 옵니다(여러 개 가능).',
  },
  {
    no: 35,
    unit: '예외 처리',
    stars: 2,
    points: 11,
    askType: '서술형',
    title: 'Checked 예외와 Unchecked 예외',
    question: 'Checked 예외와 Unchecked 예외의 차이를 서술하고 각각의 예를 쓰시오.',
    hints: ['"컴파일러가 처리하라고 강제하는가"가 기준입니다.', 'RuntimeException을 상속하면 Unchecked입니다.'],
    memorize: 'Checked는 반드시 try-catch나 throws로 처리해야 하고, Unchecked는 안 해도 컴파일된다. RuntimeException 계열이 Unchecked.',
    answer: [
      'Checked 예외는 컴파일 단계에서 반드시 처리하도록 강제되는 예외다. 처리하지 않으면 컴파일 오류가 난다.',
      '예: IOException, FileNotFoundException, ClassNotFoundException',
      'Unchecked 예외는 RuntimeException을 상속한 예외로, 처리하지 않아도 컴파일이 된다. 실행 중에 발생한다.',
      '예: NullPointerException, ArrayIndexOutOfBoundsException, ArithmeticException',
    ],
    keywords: ['Checked · 컴파일 시 처리 강제', 'Unchecked · RuntimeException 계열', '각각의 예 최소 1개씩'],
    trap: '예시를 하나도 못 쓰면 반만 맞습니다. IOException과 NullPointerException 두 개는 꼭 외워 두세요.',
  },
  {
    no: 36,
    unit: 'IO · 스트림',
    stars: 3,
    points: 11,
    askType: '서술형',
    title: '바이트 스트림과 문자 스트림',
    question: '바이트 기반 스트림과 문자 기반 스트림의 차이를 서술하고, 각각의 최상위 클래스를 쓰시오.',
    hints: ['6번 문제의 이름 규칙이 여기서 나옵니다.', '클래스 이름의 끝글자를 보면 구분됩니다.'],
    memorize: '바이트는 InputStream/OutputStream으로 끝나고 모든 파일에 쓴다. 문자는 Reader/Writer로 끝나고 텍스트에 쓴다.',
    answer: [
      '바이트 기반 스트림은 데이터를 1바이트 단위로 주고받으며 이미지·동영상 등 모든 종류의 파일을 다룰 수 있다.',
      '최상위 클래스는 InputStream과 OutputStream이며, 하위 클래스 이름이 Stream으로 끝난다.',
      '문자 기반 스트림은 데이터를 문자 단위로 주고받으며 텍스트 처리에 적합하고 한글 깨짐이 적다.',
      '최상위 클래스는 Reader와 Writer이며, 하위 클래스 이름이 Reader/Writer로 끝난다.',
    ],
    keywords: ['바이트 단위 vs 문자 단위', 'InputStream/OutputStream', 'Reader/Writer', '용도의 차이'],
    trap: '이름 규칙만 알면 처음 보는 클래스도 어느 쪽인지 맞힐 수 있습니다. FileWriter는 문자, FileOutputStream은 바이트입니다.',
  },
  {
    no: 37,
    unit: 'IO · 스트림',
    stars: 3,
    points: 11,
    askType: '빈칸',
    rote: true,
    title: '자주 나오는 IO 클래스 이름',
    question: '다음 용도에 맞는 IO 클래스 이름을 쓰시오. (1) 파일에 바이트 쓰기 (2) 파일에서 문자 읽기 (3) 파일에 문자 쓰기 (4) 버퍼로 문자 쓰기 (5) 키보드 입력을 편하게 받는 클래스',
    hints: ['6번 문제와 한 세트입니다. 이름 규칙으로 맞히세요.', '(5)는 System.in을 감싸서 쓰는 도구입니다.'],
    memorize: 'FileOutputStream, FileReader, FileWriter, BufferedWriter, Scanner. 6번의 세 개와 합쳐 여덟 개를 외우세요.',
    answer: [
      '(1) FileOutputStream : 파일에 바이트 단위로 쓴다.',
      '(2) FileReader : 파일에서 문자 단위로 읽는다.',
      '(3) FileWriter : 파일에 문자 단위로 쓴다.',
      '(4) BufferedWriter : 버퍼를 이용해 문자를 효율적으로 쓴다.',
      '(5) Scanner : System.in을 감싸 키보드 입력을 타입별로 받는다.',
    ],
    keywords: ['FileOutputStream', 'FileReader', 'FileWriter', 'BufferedWriter', 'Scanner'],
    trap: 'Buffered로 시작하는 클래스는 혼자 못 쓰고 다른 스트림을 감싸서 씁니다. new BufferedReader(new InputStreamReader(System.in)) 형태입니다.',
  },
  {
    no: 38,
    unit: 'IO · 스트림',
    stars: 2,
    points: 6,
    askType: '서술형',
    title: '스트림을 닫아야 하는 이유',
    question: 'IO 작업 후 스트림을 close()로 닫아야 하는 이유를 서술하고, 자동으로 닫는 문법을 쓰시오.',
    hints: ['닫지 않으면 무엇이 남는지 생각해 보세요.', '33번의 finally가 원래 이 일을 했습니다.'],
    memorize: '스트림은 다 쓰면 close()로 닫는다. try-with-resources를 쓰면 자동으로 닫힌다.',
    answer: [
      '스트림을 열면 시스템 자원이 할당되므로 다 쓴 뒤 close()로 반납해야 한다.',
      '닫지 않으면 자원이 계속 점유되어 메모리 낭비나 파일 잠김 문제가 생긴다.',
      '예전에는 finally 블록에서 close()를 호출했다.',
      'try-with-resources 문법인 try (자원 선언) { ... } 를 쓰면 블록이 끝날 때 자동으로 닫힌다.',
    ],
    answerCode: [
      'try (BufferedReader br = new BufferedReader(new FileReader("a.txt"))) {',
      '    System.out.println(br.readLine());',
      '} catch (IOException e) {',
      '    e.printStackTrace();',
      '}',
    ],
    keywords: ['시스템 자원 반납', '닫지 않으면 자원 낭비', 'finally에서 close()', 'try-with-resources'],
    trap: '여러 스트림을 겹쳐 썼다면 바깥쪽 하나만 닫아도 안쪽까지 함께 닫힙니다.',
  },
  {
    no: 39,
    unit: '컬렉션 · Object',
    stars: 2,
    points: 6,
    askType: '빈칸',
    rote: true,
    title: 'Object 클래스의 주요 메서드',
    question: '모든 클래스의 최상위 클래스인 Object가 제공하는 주요 메서드 3가지와 역할을 쓰시오.',
    hints: ['9번 문제에 두 개가 이미 나왔습니다.', '나머지 하나는 객체를 글자로 바꿔 주는 메서드입니다.'],
    memorize: 'toString(객체를 문자열로), equals(내용 비교), hashCode(식별 번호). 세 개만 외우면 됩니다.',
    answer: [
      'toString(): 객체의 정보를 문자열로 반환한다. 오버라이딩하지 않으면 클래스이름@해시값이 출력된다.',
      'equals(Object o): 두 객체가 같은지 비교한다. 기본은 주소 비교이므로 내용 비교를 하려면 오버라이딩한다.',
      'hashCode(): 객체의 식별 번호인 해시값을 반환한다.',
    ],
    keywords: ['toString · 문자열 반환', 'equals · 동등 비교', 'hashCode · 해시값 반환', 'Object가 최상위 클래스'],
    trap: 'equals의 기본 동작은 주소(참조) 비교입니다. "내용 비교"는 오버라이딩한 뒤의 이야기입니다.',
  },
  {
    no: 40,
    unit: '컬렉션 · Object',
    stars: 2,
    points: 11,
    askType: '코드작성',
    title: 'toString 오버라이딩',
    question: 'Player 클래스(playerName, playerNumber)의 toString()을 오버라이딩하여 "이름(등번호)" 형태로 출력되게 작성하시오.',
    hints: ['반환형은 String이고 매개변수는 없습니다.', '@Override를 위에 붙이면 점수가 더 붙습니다.'],
    memorize: 'public String toString() { return ...; } 형태. 반환형 String, 매개변수 없음.',
    answer: [
      '@Override 어노테이션을 붙이면 오버라이딩 의도가 분명해진다.',
      '접근제어자는 public, 반환형은 String, 매개변수는 없다.',
      '필드를 문자열로 이어 붙여 return한다.',
      '오버라이딩하면 System.out.println(player) 만으로 원하는 형태가 출력된다.',
    ],
    answerCode: [
      '@Override',
      'public String toString() {',
      '    return playerName + "(" + playerNumber + ")";',
      '}',
    ],
    keywords: ['@Override', 'public String toString()', '매개변수 없음', 'return으로 문자열 반환'],
    trap: 'toString은 Object의 메서드이므로 접근제어자를 protected 같은 좁은 것으로 바꿀 수 없습니다. 1번 조건 4와 이어집니다.',
  },
  {
    no: 41,
    unit: 'OOP · 상속',
    stars: 2,
    points: 6,
    askType: '결과예측',
    title: '다형성 실행 결과',
    question: '다음 코드의 실행 결과를 작성하시오.',
    questionCode: [
      'class Animal {',
      '    void sound() { System.out.println("동물 소리"); }',
      '}',
      '',
      'class Dog extends Animal {',
      '    @Override',
      '    void sound() { System.out.println("멍멍"); }',
      '}',
      '',
      'public class Main {',
      '    public static void main(String[] args) {',
      '        Animal a = new Dog();',
      '        a.sound();',
      '    }',
      '}',
    ],
    hints: ['변수 타입은 Animal인데 실제로 만들어진 객체는 Dog입니다.', '실행되는 것은 실제 객체 쪽 메서드입니다.'],
    memorize: '변수 타입이 아니라 실제로 만든 객체의 메서드가 실행된다. new 뒤에 있는 것이 답이다.',
    answer: ['멍멍'],
    keywords: ['멍멍', '동물 소리를 쓰지 않았을 것'],
    trap: '변수 타입이 Animal이라서 "동물 소리"라고 쓰는 실수가 가장 많습니다. new 뒤를 보세요.',
  },
  {
    no: 42,
    unit: '스트림',
    stars: 2,
    points: 6,
    askType: '결과예측',
    title: '스트림 filter와 map 실행 결과',
    question: '다음 코드의 실행 결과를 작성하시오.',
    questionCode: [
      'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
      '',
      'nums.stream()',
      '    .filter(n -> n % 2 == 0)',
      '    .map(n -> n * 10)',
      '    .forEach(System.out::println);',
    ],
    hints: ['filter가 먼저 걸러내고 그 다음 map이 바꿉니다. 순서대로 따라가세요.', 'n % 2 == 0은 짝수라는 뜻입니다.'],
    memorize: '거르고(filter) 바꾸고(map) 출력한다(forEach). 위에서 아래로 순서대로 따라가면 된다.',
    answer: ['20', '40'],
    keywords: ['20', '40', '두 줄만 출력'],
    trap: '걸러진 뒤 남는 것은 2와 4뿐입니다. 1, 3, 5는 map까지 가지 않습니다.',
  },
  {
    no: 43,
    unit: '예외 처리',
    stars: 2,
    points: 6,
    askType: '결과예측',
    title: 'try-catch-finally 실행 결과',
    question: '다음 코드의 실행 결과를 작성하시오.',
    questionCode: [
      'public class Main {',
      '    public static void main(String[] args) {',
      '        try {',
      '            int result = 10 / 0;',
      '            System.out.println("A");',
      '        } catch (ArithmeticException e) {',
      '            System.out.println("B");',
      '        } finally {',
      '            System.out.println("C");',
      '        }',
      '        System.out.println("D");',
      '    }',
      '}',
    ],
    hints: ['10 / 0에서 예외가 터집니다. 그 다음 줄은 실행될까요.', 'finally는 무조건 실행됩니다.'],
    memorize: '예외가 터지면 그 줄 뒤는 건너뛰고 catch로 간다. finally는 무조건, 그 뒤 코드도 계속 실행된다.',
    answer: ['B', 'C', 'D'],
    keywords: ['B', 'C', 'D', 'A는 출력되지 않음'],
    trap: 'A는 절대 출력되지 않습니다. 예외가 난 줄에서 바로 catch로 넘어가기 때문입니다.',
  },
  {
    no: 44,
    unit: '컬렉션',
    stars: 2,
    points: 6,
    askType: '결과예측',
    title: 'HashSet 중복 저장 결과',
    question: '다음 코드의 실행 결과를 작성하시오.',
    questionCode: [
      'Set<String> set = new HashSet<>();',
      'set.add("사과");',
      'set.add("바나나");',
      'set.add("사과");',
      '',
      'System.out.println(set.size());',
    ],
    hints: ['Set의 가장 큰 특징이 무엇이었는지 27번을 떠올리세요.', 'String은 equals와 hashCode가 이미 오버라이딩되어 있습니다.'],
    memorize: 'Set은 중복을 저장하지 않는다. 같은 값을 여러 번 넣어도 하나만 남는다.',
    answer: ['2'],
    keywords: ['2', '중복된 사과는 저장되지 않음'],
    trap: '3이라고 쓰면 틀립니다. add를 세 번 했어도 중복은 걸러집니다.',
  },
  {
    no: 45,
    unit: 'Java 기초',
    stars: 2,
    points: 11,
    askType: '서술형',
    title: '== 와 equals()의 차이',
    question: '== 연산자와 equals() 메서드의 차이를 서술하시오.',
    hints: ['하나는 주소를 보고 하나는 내용을 봅니다.', '39번의 Object 이야기와 이어집니다.'],
    memorize: '==는 주소를 비교하고, equals()는 내용을 비교한다. 문자열 비교는 항상 equals().',
    answer: [
      '==는 기본형일 때는 값을, 참조형일 때는 객체의 주소가 같은지를 비교한다.',
      'equals()는 Object가 제공하는 메서드로 기본 동작은 주소 비교이지만, String 등에서는 내용을 비교하도록 오버라이딩되어 있다.',
      '따라서 문자열의 내용이 같은지 확인할 때는 반드시 equals()를 써야 한다.',
    ],
    keywords: ['== · 주소(값) 비교', 'equals · 내용 비교', '문자열은 equals 사용', 'Object의 기본 equals는 주소 비교'],
    trap: '"문자열 비교는 equals" 한 줄만 확실히 써도 절반은 받습니다.',
  },
  {
    no: 46,
    unit: 'Java 기초',
    stars: 1,
    points: 6,
    askType: '서술형',
    title: 'String과 StringBuilder의 차이',
    question: 'String과 StringBuilder의 차이를 서술하시오.',
    hints: ['하나는 한 번 만들면 바뀌지 않습니다.', '문자열을 반복해서 이어 붙일 때 어느 쪽이 유리한지가 포인트입니다.'],
    memorize: 'String은 불변이라 더할 때마다 새 객체가 생기고, StringBuilder는 가변이라 같은 객체를 고쳐 쓴다.',
    answer: [
      'String은 한 번 만들어지면 값을 바꿀 수 없는 불변(immutable) 객체다. 문자열을 더하면 새 객체가 계속 만들어진다.',
      'StringBuilder는 값을 바꿀 수 있는 가변 객체로, append()로 같은 객체에 이어 붙인다.',
      '반복문 안에서 문자열을 여러 번 이어 붙일 때는 StringBuilder가 훨씬 효율적이다.',
    ],
    keywords: ['String · 불변', 'StringBuilder · 가변', '반복 연결 시 StringBuilder가 효율적', 'append()'],
    trap: 'StringBuffer도 가변입니다. 차이는 동기화 지원 여부이며, 단일 스레드에서는 StringBuilder가 빠릅니다.',
  },
  {
    no: 47,
    unit: 'Java 기초',
    stars: 2,
    points: 6,
    askType: '단답형',
    rote: true,
    title: '기본형 8가지와 참조형',
    question: '자바의 기본 자료형(primitive type) 8가지를 모두 쓰고, 참조형과의 차이를 한 줄로 쓰시오.',
    hints: ['정수 4개, 실수 2개, 문자 1개, 논리 1개입니다.', 'String은 기본형이 아닙니다.'],
    memorize: 'byte, short, int, long, float, double, char, boolean. 정수 4 · 실수 2 · 문자 1 · 논리 1.',
    answer: [
      '정수형: byte, short, int, long',
      '실수형: float, double',
      '문자형: char',
      '논리형: boolean',
      '기본형은 값 자체를 저장하고, 참조형은 객체가 있는 주소를 저장한다. String, 배열, 클래스는 모두 참조형이다.',
    ],
    keywords: ['8개 모두 나열', '기본형은 값 저장', '참조형은 주소 저장', 'String은 참조형'],
    trap: 'String을 기본형에 넣으면 감점입니다. 대문자로 시작하면 클래스, 즉 참조형입니다.',
  },
  {
    no: 48,
    unit: 'Java 기초',
    stars: 1,
    points: 6,
    askType: '서술형',
    title: '자동 형변환과 강제 형변환',
    question: '자동 형변환(묵시적)과 강제 형변환(명시적)의 차이를 서술하고 예를 쓰시오.',
    hints: ['작은 그릇에서 큰 그릇으로 옮길 때는 그냥 되고, 반대는 표시를 해야 합니다.', '강제 형변환은 괄호로 타입을 적습니다.'],
    memorize: '작은 타입 → 큰 타입은 자동, 큰 타입 → 작은 타입은 (타입)을 적어 강제로. 강제 변환은 값이 잘릴 수 있다.',
    answer: [
      '자동 형변환은 작은 크기의 타입을 큰 크기의 타입에 넣을 때 자동으로 일어난다. 예: int i = 10; double d = i;',
      '강제 형변환은 큰 타입을 작은 타입에 넣을 때 (타입)을 직접 적어 변환하는 것이다. 예: double d = 3.9; int i = (int) d;',
      '강제 형변환에서는 데이터가 잘려 값이 손실될 수 있다. 위 예에서 i는 3이 된다.',
    ],
    keywords: ['작은 것 → 큰 것은 자동', '큰 것 → 작은 것은 (타입) 명시', '값 손실 가능', '예시 코드'],
    trap: '(int) 3.9는 반올림이 아니라 소수점을 버려서 3이 됩니다.',
  },
  {
    no: 49,
    unit: 'Java 기초',
    stars: 1,
    points: 6,
    askType: '코드작성',
    title: '배열 선언과 길이',
    question: '크기가 5인 int 배열을 선언·생성하고, 배열의 길이를 출력하는 코드를 작성하시오.',
    hints: ['배열의 길이는 메서드가 아니라 필드입니다.', '괄호를 붙이지 않습니다.'],
    memorize: 'int[] arr = new int[5]; 길이는 arr.length. 괄호 없음. 문자열은 length()로 괄호가 있다.',
    answer: [
      '배열은 int[] 이름 = new int[크기]; 형태로 선언하고 생성한다.',
      '배열의 길이는 length 필드로 얻으며 괄호를 붙이지 않는다.',
      '인덱스는 0부터 시작하므로 크기가 5인 배열의 마지막 인덱스는 4다.',
    ],
    answerCode: ['int[] arr = new int[5];', '', 'System.out.println(arr.length);  // 5'],
    keywords: ['int[] 선언', 'new int[5]', 'arr.length (괄호 없음)', '인덱스는 0부터'],
    trap: '배열은 length, 문자열(String)은 length()입니다. 괄호 유무를 바꿔 쓰는 실수가 잦습니다.',
  },
  {
    no: 50,
    unit: 'OOP · 캡슐화',
    stars: 2,
    points: 11,
    askType: '서술형',
    title: 'DTO와 자바빈 규약',
    question: 'DTO가 무엇인지 서술하고, 자바빈(JavaBeans) 규약의 조건을 쓰시오.',
    hints: ['2번 문제의 Player 클래스가 바로 DTO입니다.', '규약은 세 가지입니다. 필드, 생성자, 메서드.'],
    memorize: 'DTO는 데이터를 담아 옮기는 상자. 자바빈 규약은 private 필드 + 기본 생성자 + public getter/setter.',
    answer: [
      'DTO(Data Transfer Object)는 계층 사이에서 데이터를 담아 전달하기 위한 객체다. 로직 없이 데이터만 가진다.',
      '자바빈 규약 1: 모든 필드는 private으로 선언한다.',
      '자바빈 규약 2: 매개변수가 없는 기본 생성자를 가진다.',
      '자바빈 규약 3: 필드마다 public getter와 setter를 제공한다.',
    ],
    keywords: ['데이터 전달용 객체', 'private 필드', '기본 생성자', 'public getter/setter'],
    trap: 'VO는 값 자체가 의미인 읽기 전용 객체, DAO는 데이터베이스에 접근하는 객체입니다. 셋을 구분해 두세요.',
  },
]

/** 재시험 직전에 통째로 외우고 들어갈 문장. 앞의 중요 문제에서 뽑았다. */
export const CHEAT_SHEET: Array<{ label: string; line: string }> = [
  { label: '오버라이딩', line: '이름·매개변수·반환형은 똑같이, 접근제어자는 넓게만, 예외는 좁게만' },
  { label: 'Getter/Setter', line: 'get은 받는 것 없이 돌려주고, set은 받아서 this.필드에 넣는다(void)' },
  { label: '함수형 인터페이스', line: '추상 메서드가 딱 하나. @FunctionalInterface는 컴파일러가 검사하게 하는 표식' },
  { label: 'final', line: '변수는 값 못 바꾸고, 메서드는 오버라이딩 못 하고, 클래스는 상속 못 한다' },
  { label: '추상화', line: '공통점만 뽑아 틀을 만들고 속은 감춘다. 추상 클래스와 인터페이스' },
  { label: 'IO 3형제', line: '파일 바이트 FileInputStream, 키보드 System.in, 버퍼 문자 BufferedReader' },
  { label: 'JVM', line: '자바 가상 머신. 바이트코드를 실행하고 메모리를 관리한다' },
  { label: 'main', line: 'public static void main(String[] args)' },
  { label: 'HashSet', line: 'hashCode로 번호 비교 → 같으면 equals로 내용 비교. 둘 다 Object 제공' },
  { label: 'OOP 4대', line: '캡슐화·상속·다형성·추상화. "캡상다추"' },
]
